### ISSUE TITLE
I recently started coding so i need help

### ISSUE THREAD

**Issue by adams-walter** [DinographicPixels/DPWShorts#1]
Hello,

I am a beginner, so i will need your help. I want to log/display in the logs the value that i stored.
But it does not work, here's my code :

```
DPWS.TempDBAddValue("Points", "0")

DPWS.TempDBGetValue("Points")
```
The GetValue function doesn't work.

Thanks in advance.

**Comment by pakkographic** [comment]
Hello adams-walter,

If you want to log the value you'll need to add console.log() or DPWS.Console("INFO", ) to DPWS.TempDBGetValue("Points")
```
DPWS.TempDBAddValue("Points", "0")

DPWS.Console("INFO", DPWS.TempDBGetValue("Points")) // with the DPWShorts Console
console.log(DPWS.TempDBGetValue("Points")) // with the default/javascript console

// If you want to add a text before the value you can do :
// With the DPWShorts Console :
DPWS.Console("INFO", `My value : ${DPWS.TempDBGetValue("Points")} points`) 
// With the default/javascript console : 
console.log(`My value : ${DPWS.TempDBGetValue("Points")} points`)
```

also, there's a issue with TempDBGetValue(), it cannot get the value, but i'll fix it. For the moment just test and if it returns "undefined" then it works! (just wait the new update/patch) to display your value correctly.

Hope it helps you!
If you have any other questions, you can ask me here!

**Comment by pakkographic** [comment]
I just fixed the bug, update your package 'npm update dpwshorts' and it will work correctly.

If you have any other questions, you can ask me here!

**Comment by adams-walter** [comment]
I just tested the script, it works correctly. Thanks you so much :)
I will re contact you if i need some help or found a bug
Thanks, Adams Walter.

**Comment by pakkographic** [comment]
Closed.
